CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

DROP TABLE IF EXISTS `Persona`;
DROP TABLE IF EXISTS `Vehiculo`;
DROP TABLE IF EXISTS `Asignacion`;
DROP TABLE IF EXISTS `Curso`;
DROP TABLE IF EXISTS `Matricula`;
DROP TABLE IF EXISTS `Usuario`;
DROP TABLE IF EXISTS `Rol`;
DROP TABLE IF EXISTS `Modulo`;
DROP TABLE IF EXISTS `Permiso`;

CREATE TABLE IF NOT EXISTS `Persona` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `NCedula` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellido` VARCHAR(25) NOT NULL,
  `Telefono` VARCHAR(10) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Tipo` VARCHAR(150),
  `Licencia` VARCHAR(25) NOT NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Vehiculo` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `Marca` VARCHAR(15) NOT NULL,
  `Modelo` VARCHAR(15) NOT NULL,
  `Color` VARCHAR(15) NOT NULL,
  `Circulacion` VARCHAR(20) NOT NULL,
  `Matricula` VARCHAR(10) NOT NULL
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Asignacion` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `PersonaID` INT NOT NULL,
  `VehiculoID` INT NOT NULL,
  CONSTRAINT `asignacion_personafk`
    FOREIGN KEY (`PersonaID`)
    REFERENCES `Persona` (`Id`),
  CONSTRAINT `asignacion_vehiculofk`
    FOREIGN KEY (`VehiculoID`)
    REFERENCES `Vehiculo` (`Id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Curso` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `Nombre` VARCHAR(25) NOT NULL,
  `HTeorica` INT NOT NULL,
  `HPractica` INT NOT NULL,
  `Costo` float NOT NULL
  
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Matricula` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `PersonaID` INT NOT NULL,
  `CursoID` INT NOT NULL,
  `Nota` INT,
  `Horario` VARCHAR(60),
  CONSTRAINT `matricula_personafk`
    FOREIGN KEY (`PersonaID`)
    REFERENCES `Persona` (`Id`),
  CONSTRAINT `matricula_cursofk`
    FOREIGN KEY (`CursoID`)
    REFERENCES `Curso` (`Id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

/*  Login  */

CREATE Table if NOT EXISTS `Rol` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `Nombre` VARCHAR(250) NOT NULL,
  `Descripcion` VARCHAR(250)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE Table if NOT EXISTS `Permiso` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `Tipo` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(250) NOT NULL,
  `Descripcion` VARCHAR(250)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE Table if NOT EXISTS `Modulo` (
  `Id` INT AUTO_INCREMENT PRIMARY KEY,
  `Nombre` VARCHAR(250) NOT NULL,
  `RolID` INT NOT NULL,
  `PermisoID` INT NOT NULL,
  CONSTRAINT `modulo_rolfk`
    FOREIGN KEY (`RolID`)
    REFERENCES `Rol` (`Id`),
  CONSTRAINT `modulo_permisofk`
    FOREIGN KEY (`PermisoID`)
    REFERENCES `Permiso` (`Id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE Table if NOT EXISTS `Usuario` (
  `Id` INT PRIMARY KEY,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `RolID` INT NOT NULL,
  CONSTRAINT `usuario_personafk`
    FOREIGN KEY (`Id`)
    REFERENCES `Persona` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `usuario_rolfk`
    FOREIGN KEY (`RolID`)
    REFERENCES `Rol` (`Id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
